AdRoll/rebar3_hank

src/rebar3_hank_prv.erl, test/test_app_SUITE.erl
Fix #17: format the results returned by hank.
This PR indirectly fixes #20, too.
=> Fix #17: format the results returned by hank

priv/test_files/ignore/no_ignore.erl, priv/test_files/ignore/specific_ignore.erl, priv/test_files/ignore/with_ignore.erl, priv/test_files/unused_ignored_function_params/clean.erl, priv/test_files/unused_ignored_function_params/gen_server_imp.erl, priv/test_files/unused_ignored_function_params/warnings_A.erl, priv/test_files/unused_ignored_function_params/warnings_B.erl, priv/test_files/unused_macros/unused_macro_sample.erl, priv/test_files/unused_macros/used_macro_sample.erl, priv/test_files/unused_record_fields/unused_record_field_sample.erl, priv/test_files/unused_record_fields/used_record_field_sample.erl, src/hank.erl, src/hank_utils.erl, src/rules/unused_ignored_function_params.erl, src/rules/unused_macros.erl, src/rules/unused_record_fields.erl, test/unused_macros_SUITE.erl
These are all patches for issues detected while testing Hank on our large systems.
=> [Fix #39] Try hank on our systems for hackweek

src/hank_utils.erl, src/rules/single_use_hrls.erl, src/rules/unused_hrls.erl, src/rules/unused_ignored_function_params.erl, src/rules/unused_macros.erl, src/rules/unused_record_fields.erl
Created serveral functions at `hank_utils` to avoid duplication and in some cases for future rules, since some functions are currently used from just one rule but it will be more in the future! 💪
=> [#53] Some refactor to reduce code duplication and whatnot

README.md, src/hank.erl, src/rebar3_hank_prv.erl, test/ignore_SUITE.erl
Fix #52: Allow ignoring specific rules in rebar.config
=> Fix #52: Allow ignoring specific rules in rebar.config

priv/test_files/single_use_hrl_attrs/lib/app/include/header3.hrl, priv/test_files/single_use_hrl_attrs/lib/app/src/app_other.erl, priv/test_files/single_use_hrls/include/single_unicode.hrl, priv/test_files/single_use_hrls/src/include_unicode_åö.erl, priv/test_files/unused_ignored_function_params/warnings_A.erl, priv/test_files/unused_macros/unused_macro_sample.erl, priv/test_files/unused_record_fields/unused_record_field_sample.erl, src/hank_utils.erl, src/rebar3_hank_prv.erl, src/rules/single_use_hrl_attrs.erl, src/rules/single_use_hrls.erl, src/rules/unused_ignored_function_params.erl, src/rules/unused_macros.erl, src/rules/unused_record_fields.erl, test/single_use_hrl_attrs_SUITE.erl, test/single_use_hrls_SUITE.erl, test/unused_ignored_function_params_SUITE.erl, test/unused_macros_SUITE.erl, test/unused_record_fields_SUITE.erl
=> [#58] Support for unicode characters

priv/test_files/unused_ignored_function_params/macros.erl, priv/test_files/unused_macros/double.erl, src/hank_utils.erl, src/rules/unused_ignored_function_params.erl, src/rules/unused_macros.erl, test/unused_ignored_function_params_SUITE.erl, test/unused_macros_SUITE.erl
Will merge this one since you folks are on vacation, but if you want me to revert/adjust stuff just let me know and I fix that for next versions.
This PR fixes #59 and #60
=> Fix formatting of unused params rule

priv/test_files/unused_record_fields/macros.erl, src/rules/unused_record_fields.erl, test/unused_record_fields_SUITE.erl
I'll merge this one, reviewers… But if you think it needs adjustment, leave your comments here and I'll submit a new PR soon.
=> Fix #63: Macros as record names

CONTRIBUTING.md, rebar.config
I'm using OTP 21 and don't intend to bump anytime soon and rebar3_format is in OTP21+
=> Change min otp version to 21

priv/test_files/unused_callbacks/clean.erl, src/hank_utils.erl, src/rules/unused_callbacks.erl, src/rules/unused_configuration_options.erl
Fix #81: Handle callback usage in macros
=> Fix #81: Handle callback usage in macros

src/hank.erl, src/rebar3_hank_prv.erl, test/single_use_hrls_SUITE.erl
=> Brujo's tricks

README.md
=> #88: Adding docs

src/hank.erl
Running `time rebar3 hank` in my machine…
* For 2600hz/kazoo, I get…
- **With LC:** `rebar3 hank  28.67s user 4.43s system 153% cpu 21.604 total`
- **With pmap:** `rebar3 hank  29.83s user 5.34s system 192% cpu 18.292 total`
* For erlang/otp, I get…
- **With LC:** `rebar3 hank  401.97s user 65.84s system 146% cpu 5:20.12 total`
- **With pmap:** `rebar3 hank  424.78s user 71.76s system 170% cpu 4:50.57 total`
=> [Fix #100] Parallelize file parsing

src/hank.erl, src/rebar3_hank_prv.erl
=> Put all stats together

rebar.config
* Updated `katana_code`
* Updated plugin `rebar3_hex`
* Updated plugin `rebar3_format`
**Tests result**: https://github.com/vkatsuba/rebar3_hank/runs/2501035371
=> Updated dependencies

.gitignore, priv/test_files/unused_macros/used_macro_sample.erl, src/rules/unused_macros.erl
Related to https://github.com/AdRoll/rebar3_hank/issues/117.
**Test Result:** https://github.com/vkatsuba/rebar3_hank/runs/2500838161
=> Ignore macros for case when the name provided in used macros place

priv/test_files/test_app/without_warnings/lib/a_project/src/a_folder/a_subfolder/a_module.erl, priv/test_files/test_app/without_warnings/lib/a_project/src/a_folder/a_subfolder/another_module.erl, priv/test_files/unused_macros/header.hrl, src/rules/unused_macros.erl, test/unused_macros_SUITE.erl
Fix #36: Analyze macros in header files
=> Fix #36: Analyze macros in header files

priv/test_files/unused_record_fields/header.hrl, src/rules/unused_record_fields.erl, test/unused_record_fields_SUITE.erl
Fix #33: Handle records from hrl files in unused_record_fields
=> Fix #33: Handle records from hrl files in unused_record_fields

README.md, src/hank.erl, src/rebar3_hank_prv.erl, test/hank_test_utils.erl
Fix #129: Add parsing_sytle option to rebar.config
=> Fix #129: Add parsing_sytle option to rebar.config

src/hank_utils.erl, src/rules/single_use_hrl_attrs.erl, src/rules/unused_macros.erl, test/files/single_use_hrl_attrs/lib/app/include/flow.hrl, test/files/single_use_hrl_attrs/lib/app/src/flow.erl, test/files/unused_macros/flow.erl, test/single_use_hrl_attrs_SUITE.erl
Fix #137: Handle control flow attributes
=> Fix #137: Handle control flow attributes

README.md
- Smaller Hank picture to avoid over-scrolling -> more readable
- Sample output to understand from the beginning what Hank does (and adding more rules warnings there)
- Minor changes
=> Update README with some enhancements

.github/workflows/erlang.yml, src/rules/unnecessary_function_arguments.erl, test/files/unnecessary_function_arguments/a_behaviour_imp.erl, test/files/unnecessary_function_arguments/clean.erl, test/unnecessary_function_arguments_SUITE.erl
Fix #143: Analyze private function on unknown/dynamic behavior implementations
=> Fix #143: Analyze private function on unknown/dynamic behavior implementations

src/rebar3_hank_prv.erl, test/files/hidden/.hidden.module.erl, test/files/hidden/.hidden_folder/regular_module.erl, test/files/hidden/_hidden_folder/regular_module.erl, test/files/hidden/_hidden_module.erl, test/hidden_SUITE.erl
Fix #150: Completely ignore all hidden files and folders
=> Fix #150: Completely ignore all hidden files and folders

.github/workflows/erlang.yml, rebar.config, src/hank_utils.erl, src/rules/unnecessary_function_arguments.erl, test/files/unnecessary_function_arguments/parse_transf.erl, test/unnecessary_function_arguments_SUITE.erl
(starting with parse_transform/2)
I actually created the test first, not that it matters much.
=> Allow for known functions to not be analyzed by unnecessary_function_arguments

src/hank_rule.erl, src/hank_utils.erl, src/rebar3_hank.app.src
This is for @paulo-ferraz-oliveira … to recover what we _lost_ on #152, but still not fail on the first `rebar3 dialyzer` attempt.
=> Recover some lost dialyzer analysis

src/rules/unused_configuration_options.erl, test/files/test_app/unconventional.config
Fix #157: Ignore strange config files
=> Fix #157: Ignore strange config files

rebar.config, rebar.lock
~⚠️ Don't merge yet. 😄~
The goal is to up `katana_code` in a way that this plugin can be imported without issue elsewhere.
=> Feature a new katana
